# Generated by Django 3.2.7 on 2021-09-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('CompanyID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=100)),
                ('CompanyCNPJ', models.CharField(max_length=20)),
                ('CompanyDepartment', models.CharField(max_length=50)),
                ('CompanyAdress', models.CharField(max_length=100)),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductDescription', models.CharField(max_length=100)),
                ('ProductPrice', models.CharField(max_length=50)),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
    ]
